{% set name = "gds-frameio" %}
{% set version = "3.0.1" %}

# dependencies
{% set gds_base_version = "3.0.0" %}
{% set gds_lsmp_version = "3.0.0" %}
{% set ldas_tools_al_version = "2.6.4" %}
{% set ldas_tools_framecpp_version = "2.5.8,<3.0.0a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: c04ace68dc36a1823e55329ecec31bc39254f86b9a3d596ab2fa6fcd0fbcb289

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

outputs:
  - name: gds-frameio-base
    script: build-base.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        # header needed only
        - gds-base-gdstrig
      run_exports:
        - {{ pin_subpackage("gds-frameio-base", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - make
        - gnuconfig  # [unix]
        - pkg-config
      host:
        - libboost-headers
        - gds-base >={{ gds_base_version }}
        - gds-base-gdstrig >={{ gds_base_version }}
        - gds-lsmp >={{ gds_lsmp_version }}
        - ldas-tools-al >={{ ldas_tools_al_version }}
        - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
      run:
        - gds-base >={{ gds_base_version }}
        - gds-lsmp >={{ gds_lsmp_version }}
        - ldas-tools-al
        - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
    test:
      script: test-gds-frameio-base.sh
    about:
      home: https://wiki.ligo.org/Computing/DASWG/DMT
      dev_url: https://git.ligo.org/gds/gds.git
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: GDS package frame I/O libraries
      description: |
        GDS frame I/O libraries and utilities based on FrameCPP

about:
  home: https://wiki.ligo.org/Computing/DASWG/DMT
  dev_url: https://git.ligo.org/gds/gds.git
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: GDS package frame I/O libraries
  description: |
    GDS frame I/O libraries and utilities based on FrameCPP

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
